In [1]:
import gurobipy as gp
from gurobipy import GRB
from math import sqrt
import pandas as pd
import numpy as np
import matplotlib
import sklearn.metrics as sk
#matplotlib.use('Agg')
import matplotlib.pyplot as plt

In [146]:
data = pd.read_csv('Closing_Price.csv')
stocks = data.columns
current_price = data.iloc[1,:]
stocks


Index(['INDUSINDBK.csv', 'Reliance.csv', 'Bajaj_Finserv.csv', 'Axis.csv',
       'Kotakbank.csv', 'TITAN.csv', 'TECHM.csv', 'LT.csv', 'MarutiSuzuki.csv',
       'TATASTEEL.csv', 'Bharti_Airtel.csv', 'HDFC_BANK.csv',
       'Nestle_India.csv', 'TCS.csv', 'ITC.csv', 'HEROMOTOCO.csv', 'icici.csv',
       'ONGC.csv', 'HCL.csv', 'POWERGRID.csv', 'BAJAJ-AUTO.csv', 'HU.csv',
       'Infosys.csv', 'ULTRACEMCO.csv', 'SBI.csv', 'Sun_Pharma.csv',
       'NTPC.csv', 'MnM.csv', 'AsianPaints.csv', 'HDFC.csv'],
      dtype='object')

In [3]:
closes = np.transpose(np.array(data))       # matrix of daily closing prices
absdiff = np.diff(closes)                   # change in closing price each day
reldiff = np.divide(absdiff, closes[:,:-1]) # relative change in daily closing price
delta = np.mean(reldiff, axis=1)            # mean price change
sigma = np.cov(reldiff)                     # covariance (standard deviations)
std = np.std(reldiff, axis=1)               # standard deviation

In [4]:
sigma

array([[ 3.53228677e-04,  9.22261636e-05,  1.45909840e-04,
         1.00695720e-04,  5.21394221e-05,  6.14644774e-05,
        -6.29065176e-06,  7.67871755e-05,  6.24993722e-05,
         8.44240165e-05,  6.60324922e-05,  8.19412359e-05,
         2.39618469e-05,  7.99899551e-05,  4.49873862e-05,
         5.55899316e-05,  8.26257321e-05,  5.37405085e-05,
         5.96271317e-05,  1.63952355e-05,  4.55205993e-05,
         1.45371628e-05,  8.26620221e-05,  5.71883277e-05,
         1.78804399e-04,  1.53904683e-06,  4.46494529e-05,
         7.81990658e-05,  4.06788114e-05,  8.52150891e-05],
       [ 9.22261636e-05,  1.56123476e-04,  1.07712625e-04,
         5.90524248e-05,  3.88641268e-05,  4.11617486e-05,
         4.42881123e-05,  4.65178578e-05,  4.64545580e-05,
         7.31552336e-05,  4.23019867e-05,  5.52931016e-05,
         4.49421326e-05,  5.32239679e-05,  4.72284781e-05,
         4.90099785e-05,  5.74982974e-05,  5.51374628e-05,
         5.65313535e-05,  9.94767393e-06,  4.15335101e-

In [5]:
Investing_amount = 1000000.00

In [6]:
# Correlation to Covariance
def cor_to_cov(cor, data):
    n = reldiff.shape[0]
    cov_mat = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            x, y = data[i], data[j]
            cov_mat[i][j] = cor[i][j]*(x.std() * y.std())
            
    return cov_mat
#*np.sign(np.cov(data)[i][j]

# Spearman's Cov

In [7]:
# Python3 Program to find correlation coefficient


# Utility Function to print
# a Vector
def printVector(X):
	print(*X)

# Function returns the rank vector
# of the set of observations


def rankify(X):

	N = len(X)

	# Rank Vector
	Rank_X = [None for _ in range(N)]

	for i in range(N):

		r = 1
		s = 1

		# Count no of smaller elements
		# in 0 to i-1
		for j in range(i):
			if (X[j] < X[i]):
				r += 1
			if (X[j] == X[i]):
				s += 1

		# Count no of smaller elements
		# in i+1 to N-1
		for j in range(i+1, N):
			if (X[j] < X[i]):
				r += 1
			if (X[j] == X[i]):
				s += 1

		# Use Fractional Rank formula
		# fractional_rank = r + (n-1)/2
		Rank_X[i] = r + (s-1) * 0.5

	# Return Rank Vector
	return Rank_X


# function that returns
# Pearson correlation coefficient.
def correlationCoefficient(X, Y):
	n = len(X)
	sum_X = 0
	sum_Y = 0
	sum_XY = 0
	squareSum_X = 0
	squareSum_Y = 0

	for i in range(n):

		# sum of elements of array X.
		sum_X = sum_X + X[i]

		# sum of elements of array Y.
		sum_Y = sum_Y + Y[i]

		# sum of X[i] * Y[i].
		sum_XY = sum_XY + X[i] * Y[i]

		# sum of square of array elements.
		squareSum_X = squareSum_X + X[i] * X[i]
		squareSum_Y = squareSum_Y + Y[i] * Y[i]

	# use formula for calculating
	# correlation coefficient.
	corr = (n * sum_XY - sum_X * sum_Y) / ((n * squareSum_X -
											sum_X * sum_X) * (n * squareSum_Y - sum_Y * sum_Y)) ** 0.5

	return corr


# Driver function
X = [15, 18, 21, 15, 21]
Y = [25, 25, 27, 27, 27]

# Get ranks of vector X
rank_x = rankify(X)

# Get ranks of vector y
rank_y = rankify(Y)

print("Vector X")
printVector(X)

# Print rank vector of X
print("Rankings of X")
printVector(rank_x)

# Print Vector Y
print("Vector Y")
printVector(Y)

# Print rank vector of Y
print("Rankings of Y")
printVector(rank_y)

# Print Spearmans coefficient
print("Spearman's Rank correlation: ")
print(correlationCoefficient(rank_x, rank_y))


# This code is contributed by phasing17

Vector X
15 18 21 15 21
Rankings of X
1.5 3.0 4.5 1.5 4.5
Vector Y
25 25 27 27 27
Rankings of Y
1.5 1.5 4.0 4.0 4.0
Spearman's Rank correlation: 
0.45643546458763845


In [8]:
spearman_cor = np.zeros((30,30)).tolist()
for i in range(len(stocks)):
    for j in range(len(stocks)):
        rank_i = rankify(reldiff[i])
        rank_j = rankify(reldiff[j])
        spearman_cor[i][j] =  correlationCoefficient(rank_i, rank_j)
        
spearman_cor = np.array(spearman_cor)
spearman_cor.shape

(30, 30)

In [9]:
spearman_cor

array([[ 1.        ,  0.37290984,  0.49379718,  0.38891896,  0.21806011,
         0.23715995,  0.08804301,  0.32159237,  0.31011964,  0.26232129,
         0.29508617,  0.31416465,  0.04297109,  0.3388335 ,  0.14733656,
         0.17491098,  0.32532403,  0.28085231,  0.28030195,  0.09594787,
         0.25352514,  0.04221621,  0.31238428,  0.20350377,  0.5099069 ,
         0.03570716,  0.22136605,  0.24625409,  0.20588947,  0.35024925],
       [ 0.37290984,  1.        ,  0.56207093,  0.44363339,  0.28087879,
         0.30286284,  0.26165076,  0.32084461,  0.33120638,  0.35980202,
         0.26097422,  0.32191995,  0.3313773 ,  0.36355932,  0.33745905,
         0.27697621,  0.40497792,  0.36652447,  0.31984048,  0.07189147,
         0.32134311,  0.08758012,  0.34176755,  0.370809  ,  0.34577045,
         0.02290984,  0.33672081,  0.39999288,  0.27459051,  0.41149409],
       [ 0.49379718,  0.56207093,  1.        ,  0.31952001,  0.26103831,
         0.43300812,  0.33971656,  0.26502635,  0

In [10]:
spearman_cov = cor_to_cov(spearman_cor, reldiff)

In [11]:
# Import required libraries
from scipy.stats import weightedtau
  
# Taking values from the above example in Lists
X = [1, 2, 3, 4, 5, 6, 7]
Y = [1, 3, 6, 2, 7, 4, 5]
  
# Calculating Kendall Rank correlation
corr, _ = weightedtau(X, Y)
print('Kendall Rank correlation: %.5f' % corr)
print(weightedtau(X, X))

Kendall Rank correlation: 0.34864
WeightedTauResult(correlation=1.0, pvalue=nan)


In [12]:
weightedtau_cor = np.zeros((30,30)).tolist()
for i in range(len(stocks)):
    for j in range(len(stocks)):
        weightedtau_cor[i][j] =  weightedtau(reldiff[i], reldiff[j])[0]
        
weightedtau_cor = np.array(weightedtau_cor)
weightedtau_cor.shape

(30, 30)

In [13]:
weightedtau_cov = cor_to_cov(weightedtau_cor, reldiff)
weightedtau_cor

array([[ 1.00000000e+00,  3.97630255e-01,  4.68326669e-01,
         3.49349852e-01,  3.16466763e-01,  3.44983384e-01,
        -1.64291149e-02,  4.08372833e-01,  2.92279062e-01,
         1.48163724e-01,  2.70759656e-01,  4.43288409e-01,
         2.13625821e-01,  2.68344248e-01,  2.96306572e-02,
         2.23160192e-01,  4.16537519e-01,  1.70269096e-01,
         2.36504275e-01,  2.97132709e-02,  2.22389222e-01,
         4.67993855e-02,  2.08669653e-01,  3.41466438e-01,
         5.54455870e-01, -1.78932602e-02,  1.60935275e-01,
         3.00431945e-01,  3.25014521e-01,  4.30124848e-01],
       [ 3.97630255e-01,  1.00000000e+00,  4.95843377e-01,
         4.17702534e-01,  3.71723076e-01,  2.76644350e-01,
         3.42466806e-01,  3.29797313e-01,  3.62691871e-01,
         3.57255027e-01,  2.63170071e-01,  4.27417874e-01,
         3.40547317e-01,  2.55117045e-01,  3.72339287e-01,
         4.16978579e-01,  4.65490778e-01,  5.25323215e-01,
         3.71524788e-01,  9.91433054e-02,  2.80965185e-

# Kendalltau

In [14]:
# Import required libraries
from scipy.stats import kendalltau
  
# Taking values from the above example in Lists
X = [1, 2, 3, 4, 5, 6, 7]
Y = [1, 3, 6, 2, 7, 4, 5]
  
# Calculating Kendall Rank correlation
corr, _ = kendalltau(X, Y, variant='b')
print('Kendall Rank correlation: %.5f' % corr)
print(kendalltau(X, X))

Kendall Rank correlation: 0.42857
KendalltauResult(correlation=1.0, pvalue=0.0003968253968253968)


In [15]:
Kendall_cor = np.zeros((30,30)).tolist()
for i in range(len(stocks)):
    for j in range(len(stocks)):
        Kendall_cor[i][j] =  kendalltau(reldiff[i], reldiff[j])[0]
        
Kendall_cor = np.array(Kendall_cor)
Kendall_cor.shape

(30, 30)

In [16]:
Kendall_cor

array([[ 1.        ,  0.26021934,  0.35279875,  0.27389261,  0.14855434,
         0.16479134,  0.05739923,  0.22347244,  0.20979917,  0.17170136,
         0.19982908,  0.21093861,  0.0257798 ,  0.23828514,  0.10041305,
         0.11721977,  0.22603618,  0.18576822,  0.19384703,  0.06138727,
         0.17020367,  0.03404073,  0.21806011,  0.13659023,  0.36037319,
         0.02492522,  0.14758886,  0.17276741,  0.14342686,  0.23572141],
       [ 0.26021934,  1.        ,  0.39125481,  0.3163367 ,  0.17732517,
         0.20780516,  0.18587096,  0.22831505,  0.23173337,  0.2418068 ,
         0.17789489,  0.21806011,  0.22204814,  0.23800028,  0.23572141,
         0.18814984,  0.2781655 ,  0.24873567,  0.21350235,  0.0519869 ,
         0.21777525,  0.06110241,  0.23372739,  0.25309785,  0.23018304,
         0.01951289,  0.22679679,  0.26591654,  0.18473152,  0.27873522],
       [ 0.35279875,  0.39125481,  1.        ,  0.21635095,  0.1827375 ,
         0.29525709,  0.23059393,  0.18985899,  0

In [17]:
Kendall_cov = cor_to_cov(Kendall_cor, reldiff)

# DistCor

In [18]:
from scipy.spatial.distance import pdist, squareform
import numpy as np

# from numbapro import jit, float32

def distcorr(X, Y):
    """ Compute the distance correlation function
    
    >>> a = [1,2,3,4,5]
    >>> b = np.array([1,2,9,4,4])
    >>> distcorr(a, b)
    0.762676242417
    """
    X = np.atleast_1d(X)
    Y = np.atleast_1d(Y)
    if np.prod(X.shape) == len(X):
        X = X[:, None]
    if np.prod(Y.shape) == len(Y):
        Y = Y[:, None]
    X = np.atleast_2d(X)
    Y = np.atleast_2d(Y)
    n = X.shape[0]
    if Y.shape[0] != X.shape[0]:
        raise ValueError('Number of samples must match')
    a = squareform(pdist(X))
    b = squareform(pdist(Y))
    A = a - a.mean(axis=0)[None, :] - a.mean(axis=1)[:, None] + a.mean()
    B = b - b.mean(axis=0)[None, :] - b.mean(axis=1)[:, None] + b.mean()
    
    dcov2_xy = (A * B).sum()/((n * n)*1.0)
    dcov2_xx = (A * A).sum()/((n * n)*1.0)
    dcov2_yy = (B * B).sum()/((n * n)*1.0)
    dcor = np.sqrt(dcov2_xy)/np.sqrt(np.sqrt(dcov2_xx) * np.sqrt(dcov2_yy))
    return dcor


In [19]:
dist_cor = np.zeros((30,30)).tolist()
dist_cor
for i in range(0,30):
    for j in range(0,30):
        dist_cor[i][j] = distcorr(reldiff[i], reldiff[j])

dist_cor = np.array(dist_cor)
dist_cor.shape

(30, 30)

In [20]:
dist_cor

array([[1.        , 0.37166104, 0.48438432, 0.41910386, 0.26085394,
        0.26076518, 0.19637295, 0.33574318, 0.31048924, 0.27170984,
        0.30656209, 0.34483298, 0.15194623, 0.34921386, 0.2517858 ,
        0.23225966, 0.34757419, 0.29675312, 0.29151689, 0.20204495,
        0.2820658 , 0.19167224, 0.3164548 , 0.25546   , 0.52258563,
        0.1169819 , 0.24621824, 0.2825983 , 0.26789546, 0.36925249],
       [0.37166104, 1.        , 0.54076748, 0.43634416, 0.32655954,
        0.29898075, 0.28921967, 0.3292714 , 0.3318237 , 0.36171231,
        0.27480119, 0.36805296, 0.3302324 , 0.37331957, 0.34202591,
        0.28376864, 0.39862676, 0.40779915, 0.33104828, 0.14281063,
        0.31887798, 0.14473692, 0.34143502, 0.36252511, 0.38540367,
        0.14699222, 0.32443311, 0.37238188, 0.29577033, 0.43064696],
       [0.48438432, 0.54076748, 1.        , 0.35638816, 0.30678731,
        0.41665926, 0.32816417, 0.27611713, 0.32418424, 0.28402185,
        0.17855446, 0.2924759 , 0.22130848, 0.

In [21]:
dist_cov = cor_to_cov(dist_cor, reldiff)

### MIC

In [22]:
import numpy as np
from minepy import MINE

def mic(x, y):
    m = MINE(alpha = 0.4, c = 15)
    m.compute_score(x, y)
    return m.mic()

In [23]:
mic_cor = np.zeros((30,30)).tolist()
mic_cor
for i in range(0,30):
    for j in range(0,30):
        dist_cor[i][j] = distcorr(reldiff[i], reldiff[j])

mic_cor = np.array(dist_cor)
mic_cor

array([[1.        , 0.37166104, 0.48438432, 0.41910386, 0.26085394,
        0.26076518, 0.19637295, 0.33574318, 0.31048924, 0.27170984,
        0.30656209, 0.34483298, 0.15194623, 0.34921386, 0.2517858 ,
        0.23225966, 0.34757419, 0.29675312, 0.29151689, 0.20204495,
        0.2820658 , 0.19167224, 0.3164548 , 0.25546   , 0.52258563,
        0.1169819 , 0.24621824, 0.2825983 , 0.26789546, 0.36925249],
       [0.37166104, 1.        , 0.54076748, 0.43634416, 0.32655954,
        0.29898075, 0.28921967, 0.3292714 , 0.3318237 , 0.36171231,
        0.27480119, 0.36805296, 0.3302324 , 0.37331957, 0.34202591,
        0.28376864, 0.39862676, 0.40779915, 0.33104828, 0.14281063,
        0.31887798, 0.14473692, 0.34143502, 0.36252511, 0.38540367,
        0.14699222, 0.32443311, 0.37238188, 0.29577033, 0.43064696],
       [0.48438432, 0.54076748, 1.        , 0.35638816, 0.30678731,
        0.41665926, 0.32816417, 0.27611713, 0.32418424, 0.28402185,
        0.17855446, 0.2924759 , 0.22130848, 0.

In [24]:
mic_cov = cor_to_cov(mic_cor, reldiff)

# Optimization

In [25]:
def port_opt_ret(cov, stocks, delta, method, gamma):
    m = gp.Model('portfolio')
    m.params.NonConvex = 2
    x = m.addMVar(len(stocks))
    
    portfolio_risk = x @ cov @ x
    portfolio_return = x @ delta
    print(x.shape, sigma.shape, x.shape, sep=" ", end="\n")
    print(x.shape, delta.shape, sep=" ", end="\n")
    m.setObjective(portfolio_return, GRB.MAXIMIZE)

    # Fix budget with a constraint
    m.addConstr(x.sum() == 1, 'budget')
    m.addConstr(portfolio_risk <= gamma**2, 'Risk')
    #m.addConstr(x@delta >= 0.001, 'return')

    # Verify model formulation
    m.write(str(method)+'.lp')

    # Optimize model to find the minimum risk portfolio
    m.optimize()
    
    w = x.X
    for i in range(len(stocks)):
        if(w[i] <= 1e-3):
            m.addConstr(x[i] == 0)

    m.optimize()
    
    minrisk_volatility = sqrt( x.X @ cov @ x.X)
    minrisk_return = (m.ObjVal)
    
    return x.X, minrisk_return, minrisk_volatility

In [186]:
def port_opt_ret_int(cov, stocks, delta, method, gamma):
    m = gp.Model('portfolio')
    m.params.NonConvex = 2
    x = m.addMVar(len(stocks), vtype = GRB.INTEGER, lb = 0)
    
    portfolio_risk = x @ cov @ x
    portfolio_return = x @ delta
    print(x.shape, sigma.shape, x.shape, sep=" ", end="\n")
    print(x.shape, delta.shape, sep=" ", end="\n")
    m.setObjective(portfolio_return, GRB.MAXIMIZE)

    # Fix budget with a constraint
    m.addConstr(x.sum() == 1000, 'budget')
    m.addConstr(portfolio_risk <= 1e6*gamma**2, 'Risk')
    #m.addConstr(x@delta >= 0.001, 'return')

    # Verify model formulation
    m.write(str(method)+'.lp')

    # Optimize model to find the minimum risk portfolio
    m.optimize()
      
    minrisk_volatility = sqrt( x.X @ cov @ x.X)
    minrisk_return = (m.ObjVal)
    
    return x.X, minrisk_return, minrisk_volatility

In [26]:
def port_opt_var(cov, stocks, delta, method, r):
    m = gp.Model('portfolio')
    x = m.addMVar(len(stocks))
    
    portfolio_risk = x @ cov @ x
    portfolio_return = x @ delta
    m.setObjective(portfolio_risk, GRB.MINIMIZE)

    # Fix budget with a constraint
    m.addConstr(x.sum() == 1, 'budget')
    m.addConstr(portfolio_return >= r, 'budget')
    w = x.X
    for i in range(len(stocks)):
        if(w[i] <= 1e-3):
            m.addConstr(x[i] == 0)

    m.write(str(method)+'.lp')
    m.optimize()
    # Verify model formulation
   

    # Optimize model to find the minimum risk portfolio
    m.optimize()
    minrisk_volatility = sqrt(m.ObjVal)
    minrisk_return = delta @ x.X
    return x.X, minrisk_return, minrisk_volatility

In [27]:
def port_opt_sharpe(cov, stocks, delta, method, r):
    m = gp.Model('portfolio')
    x = m.addMVar(len(stocks))
    
    portfolio_risk = x @ cov @ x
    portfolio_return = x @ delta
    print(portfolio_risk.shape, sep=" ", end="\n")
    print(portfolio_return.shape, sep=" ", end="\n")
    epsilon = 0.001
    sharpe_ratio = portfolio_return/(portfolio_risk + epsilon)
    m.setObjective(sharpe_ratio, GRB.MAXIMIZE)

    # Fix budget with a constraint
    m.addConstr(x.sum() == 1, 'budget')
    m.addConstr(portfolio_return >= r, 'budget')
    
    # Verify model formulation
    m.write(str(method)+'.lp')

    # Optimize model to find the minimum risk portfolio
    m.optimize()
    minrisk_volatility = sqrt(m.ObjVal)
    minrisk_return = delta @ x.X
    return x.X, minrisk_return, minrisk_volatility

In [154]:
def port_opt_int(cov,stocks,delta,closes,method,gamma = 0.01,budget=100000):
    m = gp.Model('portfolio')
    m.params.NonConvex = 2
    x = m.addMVar(len(stocks), vtype=GRB.INTEGER, lb = 0, name = "x")
    print(x @ closes)
    portfolio_risk = ((x @ closes) @ cov @ (x @ closes))/(budget**2)
    portfolio_return = ((x @ closes) @ delta)/budget
    print(x.shape, sigma.shape, x.shape, sep=" ", end="\n")
    print(x.shape, delta.shape, sep=" ", end="\n")
    m.setObjective(portfolio_return, GRB.MAXIMIZE)

    # Fix budget with a constraint
    m.addConstr((x @ closes).sum() <= budget, 'budget')
    m.addConstr(portfolio_risk <= gamma**2, 'Risk')
    #m.addConstr(x@delta >= 0.001, 'return')

    # Verify model formulation
    m.write(str(method)+'.lp')

    # Optimize model to find the minimum risk portfolio
    m.optimize()
    
#     w = x.X
#     for i in range(len(stocks)):
#         if(w[i] <= 1e-3):
#             m.addConstr(x[i] == 0)

#     m.optimize()
    
    maxreturn_volatility = sqrt(((x.X @ closes) @ cov @ (x.X @ closes))/(budget**2))
    maxreturn_return = (m.ObjVal)
    
    return x.X, maxreturn_return, maxreturn_volatility

In [182]:
type(data.iloc[60:120])

pandas.core.frame.DataFrame

In [29]:
import pypfopt
mu = pypfopt.expected_returns.ema_historical_return(data.iloc[60:120], returns_data=False, compounding=True, log_returns=False)
mu = mu.to_numpy()
mu = mu/252

In [30]:
port_opt_sharpe(sigma, stocks, mu, 'Pearson', 0.01)

Set parameter Username
Academic license - for non-commercial use only - expires 2024-04-25
()
()


TypeError: unsupported operand type(s) for /: 'MLinExpr' and 'MQuadExpr'

In [152]:
close_price=np.diag(closes[:,-1])
close_price

array([[ 1156.25,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ],
       [    0.  ,  2369.5 ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ],
       [    0.  ,     0.  ,  1646.6 ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  

# Min-Variance

In [31]:
port_opt_var(sigma, stocks, delta, 'Pearson', 0.00251)

GurobiError: Index 0 out of range for attribute 'X'

In [32]:
port_opt_var(dist_cov, stocks, delta, 'Distance', 0.00251)

GurobiError: Index 0 out of range for attribute 'X'

In [ ]:
port_opt_var(Kendall_cov, stocks, delta, 'Kendall', 0.00251)

In [33]:
port_opt_var(spearman_cov, stocks, delta, 'Spearman', 0.00251)

GurobiError: Index 0 out of range for attribute 'X'

# Sharpe Ratio

In [34]:
#port_opt_sharpe(sigma, stocks, delta, 'Spearman', 0.00251)

In [35]:
#port_opt_sharpe(spearman_cov, stocks, delta, 'Spearman', 0.00251)

# Max-Return

In [36]:
port_opt_ret(sigma, stocks, mu, 'Pearson', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0xadbd3a09
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.02s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.16770064, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.83229936, 0.        ]),
 0.002208908873926849,
 0.00999999146252018)

In [187]:
port_opt_ret_int(sigma, stocks, mu, 'Pearson', 0.01 )[0]

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0xdcaa2c96
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e+02, 1e+02]
Presolve time: 0.00s
Presolved: 1 rows, 30 columns, 30 nonzeros
Presolved model has 1 quadratic constraint(s)
Variable types: 0 continuous, 30 integer (0 binary)

Root relaxation: objective 2.496055e+00, 1 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds   

(array([  0.,  -0.,   0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0.,   0.,
         -0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0.,  -0., 168.,
         -0.,  -0.,  -0.,  -0.,  -0.,  -0., 832.,  -0.]),
 2.208396285691777,
 9.99774229112384)

In [191]:
return_ass = pd.DataFrame(port_opt_ret_int(sigma, stocks, delta,'Pearson', 0.01)[0])

# save the dataframe as a csv file
return_ass.to_csv("Pearson_int.csv")


Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0xc0477b06
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e+02, 1e+02]
Presolve time: 0.00s
Presolved: 1 rows, 30 columns, 30 nonzeros
Presolved model has 1 quadratic constraint(s)
Variable types: 0 continuous, 30 integer (0 binary)

Root relaxation: objective 2.501596e+00, 1 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds   

In [192]:
return_ass = pd.DataFrame(port_opt_ret_int(dist_cov, stocks, delta,'Pearson', 0.01)[0])

# save the dataframe as a csv file
return_ass.to_csv("Dist_cov_int.csv")
return_ass

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x1f2bc85f
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e+02, 1e+02]
Presolve time: 0.00s
Presolved: 1 rows, 30 columns, 30 nonzeros
Presolved model has 1 quadratic constraint(s)
Variable types: 0 continuous, 30 integer (0 binary)

Root relaxation: objective 2.095381e+00, 1 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds   

0
0    -0.0
1    -0.0
2   391.0
3    -0.0
4    -0.0
5    -0.0
6    -0.0
7    -0.0
8    -0.0
9    -0.0
10   -0.0
11   -0.0
12   -0.0
13   -0.0
14   -0.0
15  142.0
16   -0.0
17   -0.0
18   -0.0
19   -0.0
20   -0.0
21   60.0
22   -0.0
23   -0.0
24   -0.0
25   -0.0
26   -0.0
27   -0.0
28  407.0
29   -0.0

In [193]:
return_ass = pd.DataFrame(port_opt_ret_int(spearman_cov, stocks, delta, 'Pearson', 0.01)[0])

# save the dataframe as a csv file
return_ass.to_csv("Spearman_cov_int.csv")
return_ass


Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x791a3735
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [9e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e+02, 1e+02]
Presolve time: 0.00s
Presolved: 1 rows, 30 columns, 30 nonzeros
Presolved model has 1 quadratic constraint(s)
Variable types: 0 continuous, 30 integer (0 binary)

Root relaxation: objective 2.198261e+00, 1 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds   

0
0    -0.0
1    -0.0
2   430.0
3    -0.0
4    -0.0
5    -0.0
6    -0.0
7    -0.0
8    -0.0
9    -0.0
10   -0.0
11   -0.0
12   -0.0
13   -0.0
14   -0.0
15  120.0
16   -0.0
17   -0.0
18   -0.0
19   -0.0
20   -0.0
21   84.0
22   -0.0
23   -0.0
24   -0.0
25   -0.0
26   -0.0
27   -0.0
28  366.0
29   -0.0

In [195]:
return_ass = pd.DataFrame(port_opt_ret_int(Kendall_cov, stocks, delta, 'Pearson', 0.01)[0])

# save the dataframe as a csv file
return_ass.to_csv("Kendall_cov_int.csv")
return_ass


Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0xc27e0190
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e+02, 1e+02]
Presolve time: 0.00s
Presolved: 1 rows, 30 columns, 30 nonzeros
Presolved model has 1 quadratic constraint(s)
Variable types: 0 continuous, 30 integer (0 binary)

Root relaxation: objective 2.160079e+00, 1 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds   

0
0    -0.0
1    -0.0
2   450.0
3    -0.0
4    -0.0
5    -0.0
6    -0.0
7    -0.0
8    -0.0
9    -0.0
10   -0.0
11   -0.0
12   -0.0
13   -0.0
14   -0.0
15  102.0
16   -0.0
17   -0.0
18   -0.0
19   -0.0
20   -0.0
21   49.0
22   -0.0
23   -0.0
24   -0.0
25   -0.0
26   -0.0
27   -0.0
28  399.0
29   -0.0

In [171]:
return_ass = pd.DataFrame(port_opt_int(weightedtau_cov, stocks, delta, close_price,'Pearson', 0.01,100000 )[0])

# save the dataframe as a csv file
return_ass.to_csv("weightedtau_cov_int_stocks.csv")
return_ass


Set parameter NonConvex to value 2
<MLinExpr (30,)  >
array([ 1156.25 <gurobi.Var *Awaiting Model Update*>,
        2369.5 <gurobi.Var *Awaiting Model Update*>,
        1646.6 <gurobi.Var *Awaiting Model Update*>,
        722.75 <gurobi.Var *Awaiting Model Update*>,
        1783.9 <gurobi.Var *Awaiting Model Update*>,
        2574.2 <gurobi.Var *Awaiting Model Update*>,
        1005.5 <gurobi.Var *Awaiting Model Update*>,
        1819.3 <gurobi.Var *Awaiting Model Update*>,
        8547.0 <gurobi.Var *Awaiting Model Update*>,
        98.35 <gurobi.Var *Awaiting Model Update*>,
        803.35 <gurobi.Var *Awaiting Model Update*>,
        1413.2 <gurobi.Var *Awaiting Model Update*>,
        18992.6 <gurobi.Var *Awaiting Model Update*>,
        2984.95 <gurobi.Var *Awaiting Model Update*>,
        324.4 <gurobi.Var *Awaiting Model Update*>,
        2525.55 <gurobi.Var *Awaiting Model Update*>,
        848.35 <gurobi.Var *Awaiting Model Update*>,
        132.4 <gurobi.Var *Awaiting Model U

0
0    0.0
1    0.0
2   33.0
3   -0.0
4    3.0
5    0.0
6   -0.0
7   -0.0
8    0.0
9   -0.0
10   4.0
11  -0.0
12   0.0
13  -0.0
14  -0.0
15   1.0
16  -0.0
17  -0.0
18  -0.0
19  -0.0
20  -0.0
21   4.0
22   0.0
23  -0.0
24   0.0
25  -0.0
26  -0.0
27   0.0
28   5.0
29  -0.0

In [185]:
port_opt_ret_int(weightedtau_cov, close_price, stocks, delta, 'Kendall_Tau', 0.01 )

TypeError: port_opt_ret_int() takes 5 positional arguments but 6 were given

In [149]:
port_opt_ret_int(weightedtau_cov, stocks, delta, 'Kendall_Tau', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x0703e5b8
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.02s
Presolved: 872 rows, 495 columns, 2235 nonzeros
Presolved model has 30 quadratic constraint(s)
Presolved model has 435 bilinear constraint(s)
Variable types: 0 continuous, 495 integer (0 binary)

Root relaxation: objective 2.519627e+00, 1 iterations, 0.00 seconds (0.00 work units)

    N

GurobiError: Unable to retrieve attribute 'X'

In [67]:
stocks

Index(['INDUSINDBK.csv', 'Reliance.csv', 'Bajaj_Finserv.csv', 'Axis.csv',
       'Kotakbank.csv', 'TITAN.csv', 'TECHM.csv', 'LT.csv', 'MarutiSuzuki.csv',
       'TATASTEEL.csv', 'Bharti_Airtel.csv', 'HDFC_BANK.csv',
       'Nestle_India.csv', 'TCS.csv', 'ITC.csv', 'HEROMOTOCO.csv', 'icici.csv',
       'ONGC.csv', 'HCL.csv', 'POWERGRID.csv', 'BAJAJ-AUTO.csv', 'HU.csv',
       'Infosys.csv', 'ULTRACEMCO.csv', 'SBI.csv', 'Sun_Pharma.csv',
       'NTPC.csv', 'MnM.csv', 'AsianPaints.csv', 'HDFC.csv'],
      dtype='object')

In [106]:
port_opt_ret(Kendall_cov, stocks, delta, 'Kendall_Tau', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x5eda3d5d
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.00386319, 0.        , 0.44860422, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.10931081, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.04155136, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.39667043, 0.        ]),
 0.0018248625525197667,
 0.009999893090028435)

In [ ]:
port_opt_ret_int(Kendall_cov, stocks, delta, 'Kendall_Tau', 0.01 )

In [107]:
closes[:,-1].shape

(30,)

In [84]:
cov,stocks,delta,closes[-1],method,budget,gamma

NameError: name 'cov' is not defined

In [108]:
closes[:,-1]

array([ 1156.25,  2369.5 ,  1646.6 ,   722.75,  1783.9 ,  2574.2 ,
        1005.5 ,  1819.3 ,  8547.  ,    98.35,   803.35,  1413.2 ,
       18992.6 ,  2984.95,   324.4 ,  2525.55,   848.35,   132.4 ,
         930.25,   210.8 ,  3515.35,  2622.5 ,  1393.75,  6242.55,
         519.75,   944.5 ,   160.35,  1251.35,  3302.9 ,  2283.05])

array([[ 1156.25,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ],
       [    0.  ,  2369.5 ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ],
       [    0.  ,     0.  ,  1646.6 ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  ,     0.  ,     0.  ,
            0.  ,     0.  ,     0.  ,     0.  

In [117]:
port_opt_int(Kendall_cov, stocks, delta,close_price, 'Kendall_Tau',0.01,100000)

Set parameter NonConvex to value 2
<MLinExpr (30,)  >
array([ 1156.25 <gurobi.Var *Awaiting Model Update*>,
        2369.5 <gurobi.Var *Awaiting Model Update*>,
        1646.6 <gurobi.Var *Awaiting Model Update*>,
        722.75 <gurobi.Var *Awaiting Model Update*>,
        1783.9 <gurobi.Var *Awaiting Model Update*>,
        2574.2 <gurobi.Var *Awaiting Model Update*>,
        1005.5 <gurobi.Var *Awaiting Model Update*>,
        1819.3 <gurobi.Var *Awaiting Model Update*>,
        8547.0 <gurobi.Var *Awaiting Model Update*>,
        98.35 <gurobi.Var *Awaiting Model Update*>,
        803.35 <gurobi.Var *Awaiting Model Update*>,
        1413.2 <gurobi.Var *Awaiting Model Update*>,
        18992.6 <gurobi.Var *Awaiting Model Update*>,
        2984.95 <gurobi.Var *Awaiting Model Update*>,
        324.4 <gurobi.Var *Awaiting Model Update*>,
        2525.55 <gurobi.Var *Awaiting Model Update*>,
        848.35 <gurobi.Var *Awaiting Model Update*>,
        132.4 <gurobi.Var *Awaiting Model U

(array([ 0.,  0., 32., -0.,  6.,  0., -0., -0.,  0., -0.,  8., -0.,  0.,
        -0., -0.,  3., -0., -0., -0., -0., -0.,  2.,  0., -0.,  0., -0.,
        -0.,  5.,  3., -0.]),
 0.001697065016776517,
 0.010027182372300466)

In [118]:
a = port_opt_int(Kendall_cov, stocks, delta,close_price, 'Kendall_Tau',0.01,100000)[0] @close_price
a = a/100000
a

Set parameter NonConvex to value 2
<MLinExpr (30,)  >
array([ 1156.25 <gurobi.Var *Awaiting Model Update*>,
        2369.5 <gurobi.Var *Awaiting Model Update*>,
        1646.6 <gurobi.Var *Awaiting Model Update*>,
        722.75 <gurobi.Var *Awaiting Model Update*>,
        1783.9 <gurobi.Var *Awaiting Model Update*>,
        2574.2 <gurobi.Var *Awaiting Model Update*>,
        1005.5 <gurobi.Var *Awaiting Model Update*>,
        1819.3 <gurobi.Var *Awaiting Model Update*>,
        8547.0 <gurobi.Var *Awaiting Model Update*>,
        98.35 <gurobi.Var *Awaiting Model Update*>,
        803.35 <gurobi.Var *Awaiting Model Update*>,
        1413.2 <gurobi.Var *Awaiting Model Update*>,
        18992.6 <gurobi.Var *Awaiting Model Update*>,
        2984.95 <gurobi.Var *Awaiting Model Update*>,
        324.4 <gurobi.Var *Awaiting Model Update*>,
        2525.55 <gurobi.Var *Awaiting Model Update*>,
        848.35 <gurobi.Var *Awaiting Model Update*>,
        132.4 <gurobi.Var *Awaiting Model U

array([0.       , 0.       , 0.526912 , 0.       , 0.107034 , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.064268 , 0.       ,
       0.       , 0.       , 0.       , 0.0757665, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.05245  , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.0625675, 0.099087 , 0.       ])

In [38]:
port_opt_ret(Kendall_cov, stocks, mu, 'Kendall_Tau', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x4b335141
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.01s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.15015538, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.84984462, 0.        ]),
 0.002238950800735913,
 0.00999999778186033)

In [39]:
weights = port_opt_ret(Kendall_cov, stocks, mu, 'Kendall_Tau', 0.01 )[0]

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x4b335141
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

In [40]:
def convert(l,r): 
   dic={}
   for i in range(0,len(l),2):
      dic[l[i]]=r[i]

   return dic


In [41]:
name_stocks = stocks.to_list()
name_stocks[0][:-4]

'INDUSINDBK'

In [42]:
for i in range(len(name_stocks)):
    name_stocks[i] = name_stocks[i][:-4]

In [43]:
weights_dict = convert(name_stocks,list(weights))

In [44]:
weights_dict

{'INDUSINDBK': 0.0,
 'Bajaj_Finserv': 0.0,
 'Kotakbank': 0.0,
 'TECHM': 0.0,
 'MarutiSuzuki': 0.0,
 'Bharti_Airtel': 0.0,
 'Nestle_India': 0.0,
 'ITC': 0.0,
 'icici': 0.0,
 'HCL': 0.0,
 'BAJAJ-AUTO': 0.0,
 'Infosys': 0.0,
 'SBI': 0.0,
 'NTPC': 0.0,
 'AsianPaints': 0.8498446246580625}

In [45]:
l

NameError: name 'l' is not defined

In [46]:
closes.shape


(30, 120)

In [47]:
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices



latest_prices = pd.Series(closes[:,-1])

da = DiscreteAllocation(weights_dict, latest_prices, total_portfolio_value=10000)
allocation, leftover = da.greedy_portfolio()
print("Discrete allocation:", allocation)
print("Funds remaining: ${:.2f}".format(leftover))

KeyError: 'AsianPaints'

In [48]:
port_opt_ret(dist_cov, stocks, delta, 'Dist_Correlation', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x2d261c0b
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.02s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.38849174, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.14097655, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.05771428, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.41281742, 0.        ]),
 0.0017261858739918232,
 0.00999999767745302)

In [148]:
port_opt_ret_int(dist_cov, stocks, delta, 'Dist_Correlation', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x574f407d
Model has 1 quadratic constraint
Variable types: 0 continuous, 30 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 1e+03]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible or unbounded
Best objective -, best bound -, gap -


GurobiError: Unable to retrieve attribute 'X'

In [49]:
port_opt_ret(dist_cov, stocks, mu, 'Dist_Correlation', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x101e3a17
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17573412, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.82426588, 0.        ]),
 0.002195153508859417,
 0.009999999584301736)

In [50]:
port_opt_ret(spearman_cov, stocks, mu, 'Spearman', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x4cd6b95d
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [9e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.15583637, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.84416363, 0.        ]),
 0.002229223502651656,
 0.009999996912366416)

In [51]:
port_opt_ret(mic_cov, stocks, mu, 'MIC', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x101e3a17
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.17573412, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.82426588, 0.        ]),
 0.002195153508859417,
 0.009999999584301736)

In [52]:
mic_cov.shape

(30, 30)

In [53]:
stocks

Index(['INDUSINDBK.csv', 'Reliance.csv', 'Bajaj_Finserv.csv', 'Axis.csv',
       'Kotakbank.csv', 'TITAN.csv', 'TECHM.csv', 'LT.csv', 'MarutiSuzuki.csv',
       'TATASTEEL.csv', 'Bharti_Airtel.csv', 'HDFC_BANK.csv',
       'Nestle_India.csv', 'TCS.csv', 'ITC.csv', 'HEROMOTOCO.csv', 'icici.csv',
       'ONGC.csv', 'HCL.csv', 'POWERGRID.csv', 'BAJAJ-AUTO.csv', 'HU.csv',
       'Infosys.csv', 'ULTRACEMCO.csv', 'SBI.csv', 'Sun_Pharma.csv',
       'NTPC.csv', 'MnM.csv', 'AsianPaints.csv', 'HDFC.csv'],
      dtype='object')

In [54]:
port_opt_ret(0.3*spearman_cov + 0.4*Kendall_cov + 0.3*dist_cov, stocks, delta, 'Spearman', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x2f6b3096
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [6e-06, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.42580433, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.12080232, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.0598535 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.39353985, 0.        ]),
 0.00177693888215999,
 0.009999996464130441)

In [55]:
port_opt_ret(0.3*spearman_cov + 0.4*Kendall_cov + 0.3*sigma, stocks, mu, 'Spearman', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0xdc7acea9
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [6e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.15688131, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.84311869, 0.        ]),
 0.0022274343052677012,
 0.009999977601579989)

In [56]:
port_opt_ret(0.3*spearman_cov + 0.4*Kendall_cov + 0.3*sigma, stocks, delta, 'Spearman', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x391f6526
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [6e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.00s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.        , 0.        , 0.44070208, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.10724671, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.06977571, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.38227551, 0.        ]),
 0.0017924565887523288,
 0.009999667855053835)

In [57]:
def entropy(x):
    pr = np.bincount(x) / len(x)
    H = np.sum(pr * np.log2(pr))
    return -H
def crossEntropy(x,y):
    prX = np.bincount(x) / len(x)
    prY = np.bincount(y) / len(y)
    H = np.sum(prX * np.log2(prY))
    return -H
def KL_divergence(x,y):
    prX = np.bincount(x) / len(x)
    prY = np.bincount(y) / len(y)
    H = np.sum(prX * np.log2(prY))
    kl = H - entropy(x)
    return kl
def jointDist(x,y):
    N = len(x)
    u = np.unique(np.append(x,y))
    joint = []
    for i in u:
        for j in u:
            f = x[np.logical_and(x == i, y == j)]
            joint.append(len(f)/N)
    return joint
def marginalProduct(x,y):
    N = len(x)
    u = np.unique(np.append(x,y))
    marginal = []
    for i in u:
        for j in u:
            fX = len(x[x == i]) / N
            fY = len(y[y == j]) / N 
            marginal.append(fX * fY)
        
    marginal = np.array(marginal)
    return marginal
def mutualInfo(x,y):
    joint = jointDist(x,y)
    marginal = marginalProduct(x,y)
    Hjm = -np.sum(joint[list(np.where(marginal > 0))] * np.log2(marginal[list(np.where(marginal > 0).to_list())]))
    Hj = -np.sum(joint[np.where(joint > 0)] * np.log2(joint[np.where(joint > 0)]))
    return Hjm - Hj

In [58]:
marginal = marginalProduct(reldiff[0], reldiff[1])
marginal

array([0., 0., 0., ..., 0., 0., 0.])

In [59]:
joint = jointDist(reldiff[0], reldiff[1])
joint

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.008403361344537815,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,

In [60]:
import math
sum=0
Hjm = 0
for i in range(0, len(marginal)):
    if(marginal[i]>0):
        sum+=joint[i]
        Hjm +=joint[i]*log2(marginal[i])

NameError: name 'log2' is not defined

In [127]:
type(port_opt_ret(dist_cov, stocks, delta, 'Spearman', 0.01 )[1])

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x2d261c0b
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [3e-05, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.02s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

float

TypeError: float() argument must be a string or a number, not 'Var'

In [136]:
delta_60 = delta[:60]

In [144]:
delta

(30,)

In [142]:
port_opt_ret(Kendall_cov, stocks, delta_60, 'Spearman', 0.01 )

Set parameter NonConvex to value 2
(30,) (30, 30) (30,)
(30,) (30,)
Gurobi Optimizer version 10.0.1 build v10.0.1rc0 (win64)

CPU model: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 30 columns and 30 nonzeros
Model fingerprint: 0x5eda3d5d
Model has 1 quadratic constraint
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [8e-07, 4e-04]
  Objective range  [2e-05, 3e-03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e-04, 1e-04]
Presolve time: 0.02s
Presolved: 32 rows, 61 columns, 526 nonzeros
Presolved model has 1 second-order cone constraint
Ordering time: 0.00s

Barrier statistics:
 AA' NZ     : 4.950e+02
 Factor NZ  : 5.280e+02
 Factor Ops : 1.144e+04 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal         

(array([0.00386319, 0.        , 0.44860422, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.10931081, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.04155136, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.39667043, 0.        ]),
 0.0018248625525197667,
 0.009999893090028435)

In [130]:
# opt_mod = gp.Model("linear Model")
# x= opt_mod.addVar(name = 'x', vtype = GRB.CONTINUOUS,lb = 0)
# y= opt_mod.addVar(name = 'y', vtype = GRB.CONTINUOUS,lb = 0)

# port_return = port_opt_ret(float(x)*spearman_cov + float(y)*Kendall_cov + float((1-x-y))*dist_cov, stocks, delta, 'Spearman', 0.01 )[1]
# port_return
# m.setObjective(port_return, GRB.MAXIMIZE)
# m.addConstr(x<= 1, 'x-constriant')
# m.addConstr(y<= 1, 'y-constriant')
# m.addConstr(x+y<= 1, 'x+y-constriant')
# m.optimize()
# print(opt_mod.objVal)
# for v in opt_mod.getVars():
#     print((v.varName, v.x))

Set parameter NonConvex to value 2


TypeError: float() argument must be a string or a number, not 'gurobipy.LinExpr'

In [ ]:
lit = [i*0.05 for i in range(0, 50)]
results = []
lc = []
for a in lit:
    for b in lit:
        if (1-a-b > 0):
            cov = a*Kendall_cov + b*spearman_cov + dist_cov*(1-a-b) 
            results.append(port_opt_ret(cov, stocks, delta, 'Spearman', 0.01))
            lc.append((a,b))